site_name: Documentação do Sistema de Coordenação Institucional
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
